name: Build and Deploy

on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Build and Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: Webber-Lights/webberlights.com/webberlights
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets. GITHUB_TOKEN }}
          dockerfile: Dockerfile
          # buildargs: FPP_URL,
          tags: latest

      - name: Deploy package to VPS
        run: |
          ssh -o StrictHostKeyChecking=no xcraftman52@washington "
            cd /home/xcraftman52/docker
            docker login ghcr.io -u ${{ secrets.USERNAME }} -p ${{ secrets. GITHUB_TOKEN }}
            docker pull ghcr.io/webber-lights/webberlights.com/webberlights:latest
            docker compose stop webberlights && sudo docker compose rm -f webberlights
            docker system prune -f
            docker compose up webberlights -d "
